const OfferActionTypes = {
  CREATE_OFFER_START: "CREATE_OFFER_START",
  CREATE_OFFER_SUCCESS: "CREATE_OFFER_SUCCESS",
  CREATE_OFFER_FAILURE: "CREATE_OFFER_FAILURE",
  FETCH_SEND_OFFERS_START: "FETCH_SEND_OFFERS_START",
  FETCH_SEND_OFFERS_SUCCESS: "FETCH_SEND_OFFERS_SUCCESS",
  FETCH_SEND_OFFERS_FAILURE: "FETCH_SEND_OFFERS_FAILURE",
  FETCH_RECEIVED_OFFERS_START: "FETCH_RECEIVED_OFFERS_START",
  FETCH_RECEIVED_OFFERS_SUCCESS: "FETCH_RECEIVED_OFFERS_SUCCESS",
  FETCH_RECEIVED_OFFERS_FAILURE: "FETCH_RECEIVED_OFFERS_FAILURE",
};

export default OfferActionTypes;
