const ServiceActionTypes = {
  CREATE_SERVICE_START: "CREATE_SERVICE_START",
  CREATE_SERVICE_SUCCESS: "CREATE_SERVICE_SUCCESS",
  CREATE_SERVICE_FAILURE: "CREATE_SERVICE_FAILURE",
  FETCH_SERVICES_START: "FETCH_SERVICES_START",
  FETCH_SERVICES_SUCCESS: "FETCH_SERVICES_SUCCESS",
  FETCH_SERVICES_FAILURE: "FETCH_SERVICES_FAILURE",
  FETCH_USER_SERVICES_START: "FETCH_USER_SERVICES_START",
  FETCH_USER_SERVICES_SUCCESS: "FETCH_USER_SERVICES_SUCCESS",
  FETCH_USER_SERVICES_FAILURE: "FETCH_USER_SERVICES_FAILURE",
  FETCH_SERVICE_START: "FETCH_SERVICE_START",
  FETCH_SERVICE_SUCCESS: "FETCH_SERVICE_SUCCESS",
  FETCH_SERVICE_FAILURE: "FETCH_SERVICE_FAILURE",
};

export default ServiceActionTypes;
