const ServiceActionTypes = {
  CREATE_SERVICE_START: "CREATE_SERVICE_START",
  CREATE_SERVICE_SUCCESS: "CREATE_SERVICE_SUCCESS",
  CREATE_SERVICE_FAILURE: "CREATE_SERVICE_FAILURE",

}

export default ServiceActionTypes;
